psfun_dcg_vect – PSFUN
psfun_dcg_vect Subroutine
181 statements
Source File
subroutine psfun_dcg_vect(a, prec, b, eta, zeta, x, eps, desc_a, info, itmax, iter, err, itrace, istop, cond)
Uses
psb_base_mod
psb_prec_mod
psb_d_krylov_conv_mod
psb_krylov_mod
Preconditioned Conjugate Gradient for shifted system
Arguments
Type Intent Optional Attributes Name
type(psb_dspmat_type), intent(in) :: a
Distributed sparse matrix
class(psb_dprec_type), intent(inout) :: prec
Preconditioner
type(psb_d_vect_type), intent(inout) :: b
Right-hand side
real(kind=psb_dpk_), intent(in) :: eta
of
real(kind=psb_dpk_), intent(in) :: zeta
of
type(psb_d_vect_type), intent(inout) :: x
Solution on exit, initial guess on entry
real(kind=psb_dpk_), intent(in) :: eps
Tolerance for the solution
type(psb_desc_type), intent(in) :: desc_a
Descriptor
integer(kind=psb_ipk_), intent(out) :: info
Flag
integer(kind=psb_ipk_), intent(in), optional :: itmax
Auxiliary parameters
integer(kind=psb_ipk_), intent(out), optional :: iter
Final number of iteration
real(kind=psb_dpk_), intent(out), optional :: err
Auxiliary parameters
integer(kind=psb_ipk_), intent(in), optional :: itrace
Auxiliary parameters
integer(kind=psb_ipk_), intent(in), optional :: istop
Auxiliary parameters
real(kind=psb_dpk_), intent(out), optional :: cond
Auxiliary parameters
Calls
Contents
None
Call graph
psfun_dcg_vect calls psb_info, psb_erractionrestore, psb_bcast, psb_gedot, psb_check_conv, psb_init_conv, psb_get_debug_unit, psb_errpush, psb_erractionsave, psb_geaxpby, psb_spmm, psb_end_conv, psb_get_debug_level, psb_chkvect