psfun_d_serial_apply_array – PSFUN
psfun_d_serial_apply_array Subroutine
248 statements
Source File
public subroutine psfun_d_serial_apply_array(fun, a, y, x, info)
Uses
psb_base_mod
This is the core of the function apply on a serial matrix to compute . It calls on the specific routines implementing the different functions. It is the function to modify if ones want to interface a new function that was not previously available or a new algorithm (variant) for an already existing function.
INTERFACE for the John Burkardt Taylor code for the matrix exponential.
INTERFACE for the John Burkardt scaling and squaring code for the matrix exponential.
INTERFACE for the EXPOKIT package computes the matrix exponential using the irreducible rational Pade approximation to the exponential function exp(x) = r(x) = (+/-)(I + 2*(q(x)/p(x))), combined with scaling-and-squaring.
INTERFACE for the EXPOKIT package computes the matrix exponential using the partial fraction expansion of the uniform rational Chebyshev approximation for an Hessenberg matrix.
INTERFACE for the EXPOKIT package computes the matrix exponential using the partial fraction expansion of the uniform rational Chebyshev approximation for a general matrix.
INTERFACE for the EXPOKIT package computes the matrix exponential using the partial fraction expansion of the uniform rational Chebyshev approximation for a symmetric matrix.
For a symmetric matrix we need only to compute the function values, and not also its derivatives. We use LAPACK to compute the Schur decomposition of the input matrix, apply f on the eigenvalues and return the computation
Arguments
Type Intent Optional Attributes Name
class(psfun_d_serial), intent(inout) :: fun
Function information
real(kind=psb_dpk_), intent(in) :: a(:,:)
Matrix
real(kind=psb_dpk_), intent(out) :: y(:)
Output vector
real(kind=psb_dpk_), intent(in) :: x(:)
Input vector
integer(kind=psb_ipk_), intent(out) :: info
Information on the output
local variables
Calls
Contents
None
Call graph
psfun_d_serial_apply_array calls dgemv, dsyev, r8mat_expm2, psb_erractionrestore, dgchbv, psb_erractionsave, dgpadm, dschbv, r8mat_expm1, dnchbv