quadraturetest – PSFUN
quadraturetest Program
45 statements
Source File
Uses
psb_base_mod
psfun_utils_mod
psfun_quadrature_mod
Basic test for the quadrature routines from psfun_quadrature_mod
Calls
Contents
Variables
N c ctxt eta i info name quad quadformula rparams sign xi zfun
Functions
fun
Variables
Type Attributes Name Initial
integer(kind=psb_ipk_) :: N
complex(kind=psb_dpk_), allocatable, dimension(:) :: c
type(psb_ctxt_type) :: ctxt
real(kind=psb_dpk_) :: eta
integer(kind=psb_ipk_) :: i
integer(kind=psb_ipk_) :: info
character(len=20) :: name
type(psfun_z_quadrature) :: quad
procedure(zquadrule), pointer :: quadformula
real(kind=psb_dpk_) :: rparams(2)
real(kind=psb_dpk_) :: sign
complex(kind=psb_dpk_), allocatable, dimension(:) :: xi
procedure(zquadfun), pointer :: zfun
Functions
function fun(z) result(res)
Function to integrate
Arguments
Type Intent Optional Attributes Name
complex(kind=psb_dpk_), intent(in) :: z
Return Value complex(kind=psb_dpk_)
Call graph
quadraturetest calls psb_get_errstatus, psb_info, psb_init, psb_exit