serialtest – PSFUN
serialtest Program
122 statements
Source File
Uses
psb_base_mod
psfun_d_serial_mod
psb_util_mod
Test program for the serial part of the library.
This test program loads a matrix from file together with some options to test the serial computation of the matrix functions. Substantially, it test the interfacing with the library doing the serial part.
Calls
Contents
Variables
a ctxt dump fname fun iam info iunit mname n nnz np scaling t1 t2 variant x y
Subroutines
get_parms pr_usage
Variables
Type Attributes Name Initial
type(psb_dspmat_type) :: a
type(psb_ctxt_type) :: ctxt
logical :: dump
character(len=20) :: fname
type(psfun_d_serial) :: fun
integer(kind=psb_ipk_) :: iam
integer(kind=psb_ipk_) :: info
integer(kind=psb_ipk_), parameter :: iunit = 12
character(len=20) :: mname
integer(kind=psb_ipk_) :: n
integer(kind=psb_ipk_) :: nnz
integer(kind=psb_ipk_) :: np
real(kind=psb_dpk_) :: scaling
real(kind=psb_dpk_) :: t1
real(kind=psb_dpk_) :: t2
character(len=20) :: variant
real(kind=psb_dpk_), allocatable :: x(:)
real(kind=psb_dpk_), allocatable :: y(:)
Subroutines
subroutine get_parms(ctxt, mname, fname, variant, scaling, dump)
This subroutine reads the parameters needed to run the serialtest program from standard input
Arguments
Type Intent Optional Attributes Name
type(psb_ctxt_type), intent(in) :: ctxt
character(len=*), intent(out) :: mname
character(len=*), intent(out) :: fname
character(len=*), intent(out) :: variant
real(kind=psb_dpk_), intent(out) :: scaling
logical, intent(out) :: dump
subroutine pr_usage(iout)
Prints out information on incorrected program usage
Arguments
Type Intent Optional Attributes Name
integer(kind=psb_ipk_) :: iout
Call graph
serialtest calls psb_info, psb_wtime, mm_mat_read, psb_get_errstatus, mm_array_write, psb_init, get_parms, psb_exit
get_parms calls psb_toupper, psb_abort, pr_usage