utiltest – PSFUN
utiltest Program
51 statements
Source File
Uses
psb_base_mod
psfun_utils_mod
Test of the utilities distributed with the PSFUN library in psfun_utils_mod
Calls
Contents
Variables
K L ccn cdn cn coeffs csn ctxt cu dn iam info np result sn u
Variables
Type Attributes Name Initial
real(kind=psb_dpk_) :: K(2)
real(kind=psb_dpk_) :: L
complex(kind=psb_dpk_) :: ccn
complex(kind=psb_dpk_) :: cdn
real(kind=psb_dpk_) :: cn
real(kind=psb_dpk_), parameter :: coeffs(7) = (/132.0, 42.0, 14.0, 5.0, 2.0, 1.0, 0.0/)
complex(kind=psb_dpk_) :: csn
type(psb_ctxt_type) :: ctxt
complex(kind=psb_dpk_) :: cu
real(kind=psb_dpk_) :: dn
integer(kind=psb_ipk_) :: iam
integer(kind=psb_ipk_) :: info
integer(kind=psb_ipk_) :: np
real(kind=psb_dpk_) :: result
real(kind=psb_dpk_) :: sn
real(kind=psb_dpk_) :: u
Call graph
utiltest calls psb_info, psb_get_errstatus, psb_init, psb_exit, ellipj