get_parms – PSFUN
get_parms Subroutine
45 statements
Source File
subroutine get_parms(ctxt, mname, fname, variant, scaling, dump)
This subroutine reads the parameters needed to run the serialtest program from standard input
Arguments
Type Intent Optional Attributes Name
type(psb_ctxt_type), intent(in) :: ctxt
character(len=*), intent(out) :: mname
character(len=*), intent(out) :: fname
character(len=*), intent(out) :: variant
real(kind=psb_dpk_), intent(out) :: scaling
logical, intent(out) :: dump
Calls
Called by
Contents
None
Call graph
get_parms calls pr_usage, psb_toupper, psb_abort
serialtest calls get_parms