psfun_dkrylov_vect – PSFUN
psfun_dkrylov_vect Subroutine
69 statements
Source File
public subroutine psfun_dkrylov_vect(method, a, prec, b, eta, zeta, x, eps, desc_a, info, itmax, iter, err, itrace, irst, istop, cond)
Uses
psb_base_mod
psb_prec_mod
Apply Krylov method to on distributed vectors
Arguments
Type Intent Optional Attributes Name
character(len=*) :: method
type(psb_dspmat_type), intent(in) :: a
class(psb_dprec_type), intent(inout) :: prec
type(psb_d_vect_type), intent(inout) :: b
real(kind=psb_dpk_), intent(in) :: eta
real(kind=psb_dpk_), intent(in) :: zeta
type(psb_d_vect_type), intent(inout) :: x
real(kind=psb_dpk_), intent(in) :: eps
type(psb_desc_type), intent(in) :: desc_a
integer(kind=psb_ipk_), intent(out) :: info
integer(kind=psb_ipk_), intent(in), optional :: itmax
integer(kind=psb_ipk_), intent(out), optional :: iter
real(kind=psb_dpk_), intent(out), optional :: err
integer(kind=psb_ipk_), intent(in), optional :: itrace
integer(kind=psb_ipk_), intent(in), optional :: irst
integer(kind=psb_ipk_), intent(in), optional :: istop
real(kind=psb_dpk_), intent(out), optional :: cond
Calls
Called by
Contents
None
Call graph
psfun_dkrylov_vect calls psb_toupper, psb_info, psb_erractionrestore, psb_erractionsave
psb_krylov calls psfun_dkrylov_vect
shiftedtest calls psb_krylov