psfun_d_prec_init – PSFUN
psfun_d_prec_init Subroutine
23 statements
Source File
public subroutine psfun_d_prec_init(meth, ctxt, ptype, info)
Uses
psb_base_mod
amg_prec_mod
This function performs the init of the preconditioner for the inner solve in the rational Krylov method
Arguments
Type Intent Optional Attributes Name
class(psfun_d_krylov), intent(inout) :: meth
Krylov method
type(psb_ctxt_type), intent(in) :: ctxt
Parallel context
character(len=20), intent(in) :: ptype
PSBLAS/AMG4PSBLAS preconditioner
integer(kind=psb_ipk_) :: info
Result of the init call
Calls
Contents
None
Call graph
psfun_d_prec_init calls psb_erractionrestore, psb_errpush, psb_erractionsave