get_parms – PSFUN
get_parms Interface
3 statements
Source File
public interface get_parms
Get iteration parameters from the command line
Calls
Called by
Contents
Module Procedures
get_dparms
Module Procedures
public subroutine get_dparms(ctxt, mtrx_file, rhs_file, eta, zeta, filefmt, kmethd, ptype, part, afmt, istopc, itmax, itrace, irst, eps)
Get iteration parameters from the command line
Arguments
Type Intent Optional Attributes Name
type(psb_ctxt_type) :: ctxt
Parallel context
character(len=40) :: mtrx_file
character(len=40) :: rhs_file
real(kind=psb_dpk_) :: eta
real(kind=psb_dpk_) :: zeta
character(len=2) :: filefmt
Format of the file
character(len=40) :: kmethd
character(len=40) :: ptype
character(len=20) :: part
character :: afmt*5
integer(kind=psb_ipk_) :: istopc
integer(kind=psb_ipk_) :: itmax
integer(kind=psb_ipk_) :: itrace
integer(kind=psb_ipk_) :: irst
real(kind=psb_dpk_) :: eps
Call graph
get_parms calls get_dparms
get_dparms calls psb_bcast, psb_info, psb_abort
shiftedtest calls get_parms