lanczostest – PSFUN
lanczostest Program
253 statements
Source File
Uses
psb_base_mod
psfun_d_serial_mod
psfun_d_krylov_mod
psb_util_mod
Test for the parallel computation of matrix function by means of the psfun_d_lanczos function.
It applies the classical Lanczos orthogonalization algorithm on a distributed matrix.
Calls
Contents
Variables
a afmt amatsize aux_a aux_x ctxt desc_a descsize eps err filefmt fname fun i iam info ipv ircode istop iter itmax itrace iunit ivg kmethd lnp m_problem mname name np part perm res rhs_file scaling system_size t1 t2 variant x_col x_col_glob y_col
Subroutines
get_parms pr_usage
Variables
Type Attributes Name Initial
type(psb_dspmat_type) :: a
character(len=20) :: afmt
integer(kind=psb_epk_) :: amatsize
type(psb_ldspmat_type) :: aux_a
real(kind=psb_dpk_), allocatable, target :: aux_x(:,:)
type(psb_ctxt_type) :: ctxt
type(psb_desc_type) :: desc_a
integer(kind=psb_epk_) :: descsize
real(kind=psb_dpk_) :: eps
real(kind=psb_dpk_) :: err
character(len=20) :: filefmt
character(len=20) :: fname
type(psfun_d_serial) :: fun
integer(kind=psb_ipk_) :: i
integer(kind=psb_ipk_) :: iam
integer(kind=psb_ipk_) :: info
integer(kind=psb_ipk_), allocatable :: ipv(:)
integer(kind=psb_ipk_) :: ircode
integer(kind=psb_ipk_) :: istop
integer(kind=psb_ipk_) :: iter
integer(kind=psb_ipk_) :: itmax
integer(kind=psb_ipk_) :: itrace
integer(kind=psb_ipk_), parameter :: iunit = 12
integer(kind=psb_ipk_), allocatable :: ivg(:)
type(psfun_d_krylov) :: kmethd
integer(kind=psb_lpk_) :: lnp
integer(kind=psb_ipk_) :: m_problem
character(len=20) :: mname
character(len=20) :: name
integer(kind=psb_ipk_) :: np
character(len=20) :: part
integer(kind=psb_ipk_), allocatable :: perm(:)
real(kind=psb_dpk_), allocatable :: res(:)
character(len=20) :: rhs_file
real(kind=psb_dpk_) :: scaling
integer(kind=psb_epk_) :: system_size
real(kind=psb_dpk_) :: t1
real(kind=psb_dpk_) :: t2
character(len=20) :: variant
type(psb_d_vect_type) :: x_col
real(kind=psb_dpk_), pointer :: x_col_glob(:)
type(psb_d_vect_type) :: y_col
Subroutines
subroutine get_parms(ctxt, mname, rhs_file, filefmt, part, afmt, fname, variant, scaling, eps, itmax, itrace, istop)
This subroutine reads the parameters needed to run the lanczostest program from standard input
Arguments
Type Intent Optional Attributes Name
type(psb_ctxt_type), intent(in) :: ctxt
character(len=*), intent(out) :: mname
character(len=*), intent(out) :: rhs_file
character(len=*), intent(out) :: filefmt
character(len=*), intent(out) :: part
character(len=*), intent(out) :: afmt
character(len=*), intent(out) :: fname
character(len=*), intent(out) :: variant
real(kind=psb_dpk_), intent(out) :: scaling
real(kind=psb_dpk_), intent(out) :: eps
integer(kind=psb_ipk_), intent(out) :: itmax
integer(kind=psb_ipk_), intent(out) :: itrace
integer(kind=psb_ipk_), intent(out) :: istop
subroutine pr_usage(iout)
Prints out information on incorrected program usage
Arguments
Type Intent Optional Attributes Name
integer(kind=psb_ipk_) :: iout
Call graph
lanczostest calls psb_info, mm_mat_read, psb_toupper, hb_read, mm_array_read, psb_matdist, psb_spfree, psb_geasb, distr_mtpart, psb_amx, psb_geall, get_parms, psb_exit, psb_sum, psb_wtime, psb_realloc, psb_gefree, psb_errpush, psb_abort, psb_init, psb_barrier, psb_scatter, psb_bcast, psb_cdfree, psb_get_errstatus, build_mtpart, getv_mtpart
get_parms calls psb_info, psb_abort, psb_bcast, pr_usage