shiftedtest – PSFUN
shiftedtest Program
198 statements
Source File
Uses
psb_base_mod
psb_prec_mod
psb_krylov_mod
psb_util_mod
psfun_krylov_mod
getp
Test program for the shifted Krylov methods from psfun_krylov_mod
Calls
Contents
Variables
a afmt amatsize aux_a aux_b b_amax b_col b_col_glob cond ctxt d desc_a descsize dim eps err err_act eta filefmt fname fnout i iam ierr ii info internal iparm ipv ircode irst istopc iter itmax itrace iunit ivg j kmethd lnp m m_problem methd mtrx_file n_row name ne nnzero np nrhs nrow nv part prec precsize ptype r_amax r_col r_col_glob resmx resmxp rhs_file scale t1 t2 tprec x_col x_col_glob zeta
Variables
Type Attributes Name Initial
type(psb_dspmat_type) :: a
character(len=5) :: afmt
integer(kind=psb_epk_) :: amatsize
type(psb_ldspmat_type) :: aux_a
real(kind=psb_dpk_), allocatable, target :: aux_b(:,:)
real(kind=psb_dpk_) :: b_amax
type(psb_d_vect_type) :: b_col
real(kind=psb_dpk_), pointer :: b_col_glob(:)
real(kind=psb_dpk_) :: cond
type(psb_ctxt_type) :: ctxt
real(kind=psb_dpk_), allocatable, target :: d(:)
type(psb_desc_type) :: desc_a
integer(kind=psb_epk_) :: descsize
integer(kind=psb_ipk_) :: dim
real(kind=psb_dpk_) :: eps
real(kind=psb_dpk_) :: err
integer(kind=psb_ipk_) :: err_act
real(kind=psb_dpk_) :: eta
character(len=2) :: filefmt
character(len=40) :: fname
character(len=40) :: fnout
integer(kind=psb_ipk_) :: i
integer(kind=psb_ipk_) :: iam
integer(kind=psb_ipk_) :: ierr
integer(kind=psb_ipk_) :: ii
integer(kind=psb_ipk_) :: info
integer(kind=psb_ipk_) :: internal
integer(kind=psb_ipk_) :: iparm(20)
integer(kind=psb_ipk_), allocatable :: ipv(:)
integer(kind=psb_ipk_) :: ircode
integer(kind=psb_ipk_) :: irst
integer(kind=psb_ipk_) :: istopc
integer(kind=psb_ipk_) :: iter
integer(kind=psb_ipk_) :: itmax
integer(kind=psb_ipk_) :: itrace
integer(kind=psb_ipk_), parameter :: iunit = 12
integer(kind=psb_ipk_), allocatable :: ivg(:)
integer(kind=psb_ipk_) :: j
character(len=40) :: kmethd
integer(kind=psb_lpk_) :: lnp
integer(kind=psb_ipk_) :: m
integer(kind=psb_ipk_) :: m_problem
integer(kind=psb_ipk_) :: methd
character(len=40) :: mtrx_file
integer(kind=psb_ipk_) :: n_row
character(len=20) :: name
integer(kind=psb_ipk_) :: ne
integer(kind=psb_ipk_) :: nnzero
integer(kind=psb_ipk_) :: np
integer(kind=psb_ipk_) :: nrhs
integer(kind=psb_ipk_) :: nrow
integer(kind=psb_ipk_) :: nv
character(len=20) :: part
type(psb_dprec_type) :: prec
integer(kind=psb_epk_) :: precsize
character(len=40) :: ptype
real(kind=psb_dpk_) :: r_amax
type(psb_d_vect_type) :: r_col
real(kind=psb_dpk_), allocatable, save :: r_col_glob(:)
real(kind=psb_dpk_) :: resmx
real(kind=psb_dpk_) :: resmxp
character(len=40) :: rhs_file
real(kind=psb_dpk_) :: scale
real(kind=psb_dpk_) :: t1
real(kind=psb_dpk_) :: t2
real(kind=psb_dpk_) :: tprec
type(psb_d_vect_type) :: x_col
real(kind=psb_dpk_), allocatable, save :: x_col_glob(:)
real(kind=psb_dpk_) :: zeta
Call graph
shiftedtest calls psb_info, mm_mat_read, psb_krylov, psb_toupper, psb_geamax, hb_read, mm_array_read, psb_matdist, psb_errstatus_fatal, get_parms, psb_spfree, psb_geasb, psb_set_errverbosity, distr_mtpart, psb_amx, psb_geall, psb_geaxpby, psb_exit, psb_sum, psb_wtime, psb_realloc, 4, psb_gefree, psb_errpush, psb_abort, psb_init, psb_spmm, psb_barrier, psb_scatter, psb_bcast, psb_cdfree, psb_genrm2, build_mtpart, psb_gather, getv_mtpart
psb_krylov calls psfun_dkrylov_vect
get_parms calls get_dparms
psfun_dkrylov_vect calls psb_info, psb_toupper, psb_erractionrestore, psb_erractionsave
get_dparms calls psb_info, psb_abort, psb_bcast