find_library(GNUPLOTFORTRANLIB libgnuplotfortran.a PATHS ${GNUPLOTFORTRAN_DIR})

if(GNUPLOTFORTRAN_DIR)
  SET(LINKGNUPLOTFORTRAN -L${GNUPLOTFORTRAN_DIR} -lgnuplotfortran -lfortranposix)
  SET(INCLUDEGNUPLOTFORTRAN ${GNUPLOTFORTRAN_DIR})
  SET(GNUPLOTFORTRANDEFINES WITHGNUPLOTFORTRAN)
else()
  message("I did not find GNUPLOTFORTRAN! Everything will fail")
endif()
